version: 1.0.{build}
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2019
configuration: Release
before_build:
- nuget restore TargetFrameworkMigrator.sln -verbosity quiet
build:
  project: TargetFrameworkMigrator.sln
  parallel: true
  verbosity: minimal
test:
  assemblies:
    only:
    - '**/TargetFrameworkMigrator_UnitTests.dll'
artifacts:
- path: Src\TargetFrameworkMigratorVSIX\**\*.vsix
